# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkingspace',
            unique_together=set([('latitude', 'longitude')]),
        ),
    ]
